# Generated by Django 4.0.4 on 2022-05-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Apellido', models.CharField(max_length=40)),
                ('Edad', models.IntegerField()),
                ('Parentesco', models.CharField(max_length=40)),
            ],
        ),
    ]
